### ISSUE TITLE
different union lvl

### ISSUE THREAD

**Issue by rewitte** [xAkre/Wuthering-Waves-RPC#13]
![image](https://github.com/xAkre/Wuthering-Waves-RPC/assets/55956074/8275ccbe-8c02-40f1-90a7-2b8a26569368)
log in again into acc didnt help and reopnening wuwa 
[log.txt](https://github.com/user-attachments/files/15721935/log.txt)

**Comment by xAkre** [comment]
Did you happen to log in to an account that had union level 37 on your computer before?

**Comment by rewitte** [comment]
yeah yesterday

**Comment by rewitte** [comment]
ik this is the case but still why it trying to use db with higher UL isnt it should use the last one that was used

**Comment by xAkre** [comment]
That would be ideal, but the last modified file doesn't necessarily have the latest union level. I will look into this once i get home

**Comment by xAkre** [comment]
It seems there is a 
```
RecentlyLoginUID
```
key and a 
```
LoginTime_{user_id}
```
key in LocalStorage, the latter of which seems to contain a timestamp of when the account with the id was last logged in. This could be used to figure out which account is currently in use. I will try to find the time tomorrow to go about implementing it

**Comment by xAkre** [comment]
This is proving harder than expected because the `RecentlyLoginUID` key stores the player's Wuthering Waves UID, but union level data is, for some reason, linked with the player's KuroGames UID, and there doesn't seem to be a way to connect the Wuthering Waves UID to the KuroGames UID. This wouldn't be a problem if either the `SdkLevelData` key or `SdkLastTimeLoginData` key was updated when a different account was logged in, but that only seems to be the case when a **new** account is added, then it is appended to the end of the array

**Comment by xAkre** [comment]
The RPC currently goes over every LocalStorage file, gets the latest entry from `SdkLevelData`, then gets the highest union level among the files. This does cause it to display the incorrect union level when you log into a **new** account with a higher UL and then log back into an older account with a lower union level. If there is no way to connect a KuroGames ID to a Wuthering Waves ID, then the only other way I can think of that fixes the issue is to allow the user to specify a KuroGames ID they want to RPC to check for when getting the union level

**Comment by rewitte** [comment]
it would be so much better if we could just select the account we want to use. looks a way more convenient

**Comment by xAkre** [comment]
The option to specify what Kuro Games UID the RPC should look for is available in [v1.1.5](https://github.com/xAkre/Wuthering-Waves-RPC/releases/tag/v1.1.5)
